"""Derive unmodified Knock Out Prize awards from current printed profiles.

This layer supplies the base printed Prize value only. Replacement/reduction
semantics such as Legacy Energy remain separate live effects.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

from knockout_phase_resolution import TwoPlayerKnockOutPhase
from pokemon_card_profile import PokemonCardProfile
from stack_board_profile_binding import (
    current_profile,
    validate_current_print_bindings,
)


@dataclass(frozen=True)
class PrintedPrizeBatch:
    victim_player_id: str
    winner_player_id: str
    knocked_out_values: tuple[tuple[str, int], ...]

    @property
    def total(self) -> int:
        return sum(value for _pokemon_id, value in self.knocked_out_values)


def printed_prize_batches(
    phase: TwoPlayerKnockOutPhase,
    *,
    profiles: Mapping[str, PokemonCardProfile],
    current_print_ids: Mapping[str, Mapping[str, str]],
) -> tuple[PrintedPrizeBatch, PrintedPrizeBatch]:
    """Return the base printed Prize award generated by each player's KO batch."""

    ids = tuple(side.player_id for side in phase.sides)
    if len(ids) != 2 or len(set(ids)) != 2:
        raise ValueError("exactly two player sides are required")
    if set(current_print_ids) != set(ids):
        raise ValueError("current_print_ids must contain exactly both players")

    opponent = {ids[0]: ids[1], ids[1]: ids[0]}
    batches: list[PrintedPrizeBatch] = []

    for side in phase.sides:
        board = side.pending.state.board
        assert board is not None
        bindings = current_print_ids[side.player_id]
        validate_current_print_bindings(board, bindings)

        values = tuple(
            (
                pokemon_id,
                current_profile(
                    pokemon_id,
                    profiles,
                    bindings,
                ).prize_value,
            )
            for pokemon_id in side.pending.knocked_out_ids
        )
        batches.append(
            PrintedPrizeBatch(
                victim_player_id=side.player_id,
                winner_player_id=opponent[side.player_id],
                knocked_out_values=values,
            )
        )

    return batches[0], batches[1]


def printed_prize_awards(
    phase: TwoPlayerKnockOutPhase,
    *,
    profiles: Mapping[str, PokemonCardProfile],
    current_print_ids: Mapping[str, Mapping[str, str]],
) -> dict[str, int]:
    """Map each player to the base printed Prizes earned from the opponent."""

    awards = {side.player_id: 0 for side in phase.sides}
    for batch in printed_prize_batches(
        phase,
        profiles=profiles,
        current_print_ids=current_print_ids,
    ):
        awards[batch.winner_player_id] += batch.total
    return awards
